# Generated by Django 5.1.7 on 2025-06-01 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_feedbackform_assigned_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_feedback_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
