# Generated by Django 5.1.7 on 2025-06-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_feedbackform_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='form',
            new_name='feedback_form',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, help_text='Comma-separated options (only for poll questions)'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('poll', 'Poll'), ('rating', 'Rating')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
