# Generated by Django 5.1.7 on 2025-06-01 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_feedbackresponse_alter_answer_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='feedback_form',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.feedbackform'),
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('PARAGRAPH', 'Paragraph'), ('CHECKBOX', 'Checkbox'), ('RATING', 'Rating')], max_length=20)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options (for MCQ and CHECKBOX)')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='base.feedbackform')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.feedbackresponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.feedbackquestion')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
